// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobufUtils.proto

package protobufUtils;

public final class ProtobufUtils {
  private ProtobufUtils() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PGRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobufUtils.PGRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string Code = 1;</code>
     *
     * <pre>
     * for different kind of opration
     * </pre>
     */
    boolean hasCode();
    /**
     * <code>required string Code = 1;</code>
     *
     * <pre>
     * for different kind of opration
     * </pre>
     */
    java.lang.String getCode();
    /**
     * <code>required string Code = 1;</code>
     *
     * <pre>
     * for different kind of opration
     * </pre>
     */
    com.google.protobuf.ByteString
        getCodeBytes();

    /**
     * <code>optional string errorInfo = 2;</code>
     *
     * <pre>
     * "succed" for a successful post or get, other word for an error 
     * </pre>
     */
    boolean hasErrorInfo();
    /**
     * <code>optional string errorInfo = 2;</code>
     *
     * <pre>
     * "succed" for a successful post or get, other word for an error 
     * </pre>
     */
    java.lang.String getErrorInfo();
    /**
     * <code>optional string errorInfo = 2;</code>
     *
     * <pre>
     * "succed" for a successful post or get, other word for an error 
     * </pre>
     */
    com.google.protobuf.ByteString
        getErrorInfoBytes();

    /**
     * <code>optional string username = 3;</code>
     */
    boolean hasUsername();
    /**
     * <code>optional string username = 3;</code>
     */
    java.lang.String getUsername();
    /**
     * <code>optional string username = 3;</code>
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    /**
     * <code>optional string password = 4;</code>
     */
    boolean hasPassword();
    /**
     * <code>optional string password = 4;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>optional string password = 4;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <code>optional string score = 5;</code>
     */
    boolean hasScore();
    /**
     * <code>optional string score = 5;</code>
     */
    java.lang.String getScore();
    /**
     * <code>optional string score = 5;</code>
     */
    com.google.protobuf.ByteString
        getScoreBytes();

    /**
     * <code>repeated string pictures = 6;</code>
     */
    com.google.protobuf.ProtocolStringList
        getPicturesList();
    /**
     * <code>repeated string pictures = 6;</code>
     */
    int getPicturesCount();
    /**
     * <code>repeated string pictures = 6;</code>
     */
    java.lang.String getPictures(int index);
    /**
     * <code>repeated string pictures = 6;</code>
     */
    com.google.protobuf.ByteString
        getPicturesBytes(int index);

    /**
     * <code>repeated string picturesID = 7;</code>
     */
    com.google.protobuf.ProtocolStringList
        getPicturesIDList();
    /**
     * <code>repeated string picturesID = 7;</code>
     */
    int getPicturesIDCount();
    /**
     * <code>repeated string picturesID = 7;</code>
     */
    java.lang.String getPicturesID(int index);
    /**
     * <code>repeated string picturesID = 7;</code>
     */
    com.google.protobuf.ByteString
        getPicturesIDBytes(int index);

    /**
     * <code>optional .protobufUtils.PGRequest.RankInfo rankInfo = 8;</code>
     */
    boolean hasRankInfo();
    /**
     * <code>optional .protobufUtils.PGRequest.RankInfo rankInfo = 8;</code>
     */
    protobufUtils.ProtobufUtils.PGRequest.RankInfo getRankInfo();
    /**
     * <code>optional .protobufUtils.PGRequest.RankInfo rankInfo = 8;</code>
     */
    protobufUtils.ProtobufUtils.PGRequest.RankInfoOrBuilder getRankInfoOrBuilder();

    /**
     * <code>optional string nickname = 9;</code>
     */
    boolean hasNickname();
    /**
     * <code>optional string nickname = 9;</code>
     */
    java.lang.String getNickname();
    /**
     * <code>optional string nickname = 9;</code>
     */
    com.google.protobuf.ByteString
        getNicknameBytes();
  }
  /**
   * Protobuf type {@code protobufUtils.PGRequest}
   */
  public static final class PGRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobufUtils.PGRequest)
      PGRequestOrBuilder {
    // Use PGRequest.newBuilder() to construct.
    private PGRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PGRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PGRequest defaultInstance;
    public static PGRequest getDefaultInstance() {
      return defaultInstance;
    }

    public PGRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PGRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              code_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              errorInfo_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              username_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              password_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              score_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                pictures_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000020;
              }
              pictures_.add(bs);
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                picturesID_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000040;
              }
              picturesID_.add(bs);
              break;
            }
            case 66: {
              protobufUtils.ProtobufUtils.PGRequest.RankInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000020) == 0x00000020)) {
                subBuilder = rankInfo_.toBuilder();
              }
              rankInfo_ = input.readMessage(protobufUtils.ProtobufUtils.PGRequest.RankInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(rankInfo_);
                rankInfo_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000020;
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              nickname_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          pictures_ = pictures_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          picturesID_ = picturesID_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobufUtils.ProtobufUtils.internal_static_protobufUtils_PGRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobufUtils.ProtobufUtils.internal_static_protobufUtils_PGRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobufUtils.ProtobufUtils.PGRequest.class, protobufUtils.ProtobufUtils.PGRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<PGRequest> PARSER =
        new com.google.protobuf.AbstractParser<PGRequest>() {
      public PGRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PGRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PGRequest> getParserForType() {
      return PARSER;
    }

    public interface RankInfoOrBuilder extends
        // @@protoc_insertion_point(interface_extends:protobufUtils.PGRequest.RankInfo)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string myRank = 1;</code>
       */
      boolean hasMyRank();
      /**
       * <code>required string myRank = 1;</code>
       */
      java.lang.String getMyRank();
      /**
       * <code>required string myRank = 1;</code>
       */
      com.google.protobuf.ByteString
          getMyRankBytes();

      /**
       * <code>repeated string topUser = 2;</code>
       */
      com.google.protobuf.ProtocolStringList
          getTopUserList();
      /**
       * <code>repeated string topUser = 2;</code>
       */
      int getTopUserCount();
      /**
       * <code>repeated string topUser = 2;</code>
       */
      java.lang.String getTopUser(int index);
      /**
       * <code>repeated string topUser = 2;</code>
       */
      com.google.protobuf.ByteString
          getTopUserBytes(int index);

      /**
       * <code>repeated string topScore = 3;</code>
       */
      com.google.protobuf.ProtocolStringList
          getTopScoreList();
      /**
       * <code>repeated string topScore = 3;</code>
       */
      int getTopScoreCount();
      /**
       * <code>repeated string topScore = 3;</code>
       */
      java.lang.String getTopScore(int index);
      /**
       * <code>repeated string topScore = 3;</code>
       */
      com.google.protobuf.ByteString
          getTopScoreBytes(int index);
    }
    /**
     * Protobuf type {@code protobufUtils.PGRequest.RankInfo}
     */
    public static final class RankInfo extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:protobufUtils.PGRequest.RankInfo)
        RankInfoOrBuilder {
      // Use RankInfo.newBuilder() to construct.
      private RankInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private RankInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final RankInfo defaultInstance;
      public static RankInfo getDefaultInstance() {
        return defaultInstance;
      }

      public RankInfo getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private RankInfo(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                myRank_ = bs;
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                  topUser_ = new com.google.protobuf.LazyStringArrayList();
                  mutable_bitField0_ |= 0x00000002;
                }
                topUser_.add(bs);
                break;
              }
              case 26: {
                com.google.protobuf.ByteString bs = input.readBytes();
                if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                  topScore_ = new com.google.protobuf.LazyStringArrayList();
                  mutable_bitField0_ |= 0x00000004;
                }
                topScore_.add(bs);
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
            topUser_ = topUser_.getUnmodifiableView();
          }
          if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
            topScore_ = topScore_.getUnmodifiableView();
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobufUtils.ProtobufUtils.internal_static_protobufUtils_PGRequest_RankInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobufUtils.ProtobufUtils.internal_static_protobufUtils_PGRequest_RankInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobufUtils.ProtobufUtils.PGRequest.RankInfo.class, protobufUtils.ProtobufUtils.PGRequest.RankInfo.Builder.class);
      }

      public static com.google.protobuf.Parser<RankInfo> PARSER =
          new com.google.protobuf.AbstractParser<RankInfo>() {
        public RankInfo parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new RankInfo(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<RankInfo> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int MYRANK_FIELD_NUMBER = 1;
      private java.lang.Object myRank_;
      /**
       * <code>required string myRank = 1;</code>
       */
      public boolean hasMyRank() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string myRank = 1;</code>
       */
      public java.lang.String getMyRank() {
        java.lang.Object ref = myRank_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            myRank_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string myRank = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMyRankBytes() {
        java.lang.Object ref = myRank_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          myRank_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int TOPUSER_FIELD_NUMBER = 2;
      private com.google.protobuf.LazyStringList topUser_;
      /**
       * <code>repeated string topUser = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getTopUserList() {
        return topUser_;
      }
      /**
       * <code>repeated string topUser = 2;</code>
       */
      public int getTopUserCount() {
        return topUser_.size();
      }
      /**
       * <code>repeated string topUser = 2;</code>
       */
      public java.lang.String getTopUser(int index) {
        return topUser_.get(index);
      }
      /**
       * <code>repeated string topUser = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTopUserBytes(int index) {
        return topUser_.getByteString(index);
      }

      public static final int TOPSCORE_FIELD_NUMBER = 3;
      private com.google.protobuf.LazyStringList topScore_;
      /**
       * <code>repeated string topScore = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getTopScoreList() {
        return topScore_;
      }
      /**
       * <code>repeated string topScore = 3;</code>
       */
      public int getTopScoreCount() {
        return topScore_.size();
      }
      /**
       * <code>repeated string topScore = 3;</code>
       */
      public java.lang.String getTopScore(int index) {
        return topScore_.get(index);
      }
      /**
       * <code>repeated string topScore = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTopScoreBytes(int index) {
        return topScore_.getByteString(index);
      }

      private void initFields() {
        myRank_ = "";
        topUser_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        topScore_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasMyRank()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getMyRankBytes());
        }
        for (int i = 0; i < topUser_.size(); i++) {
          output.writeBytes(2, topUser_.getByteString(i));
        }
        for (int i = 0; i < topScore_.size(); i++) {
          output.writeBytes(3, topScore_.getByteString(i));
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getMyRankBytes());
        }
        {
          int dataSize = 0;
          for (int i = 0; i < topUser_.size(); i++) {
            dataSize += com.google.protobuf.CodedOutputStream
              .computeBytesSizeNoTag(topUser_.getByteString(i));
          }
          size += dataSize;
          size += 1 * getTopUserList().size();
        }
        {
          int dataSize = 0;
          for (int i = 0; i < topScore_.size(); i++) {
            dataSize += com.google.protobuf.CodedOutputStream
              .computeBytesSizeNoTag(topScore_.getByteString(i));
          }
          size += dataSize;
          size += 1 * getTopScoreList().size();
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static protobufUtils.ProtobufUtils.PGRequest.RankInfo parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static protobufUtils.ProtobufUtils.PGRequest.RankInfo parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static protobufUtils.ProtobufUtils.PGRequest.RankInfo parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static protobufUtils.ProtobufUtils.PGRequest.RankInfo parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static protobufUtils.ProtobufUtils.PGRequest.RankInfo parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static protobufUtils.ProtobufUtils.PGRequest.RankInfo parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static protobufUtils.ProtobufUtils.PGRequest.RankInfo parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static protobufUtils.ProtobufUtils.PGRequest.RankInfo parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static protobufUtils.ProtobufUtils.PGRequest.RankInfo parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static protobufUtils.ProtobufUtils.PGRequest.RankInfo parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(protobufUtils.ProtobufUtils.PGRequest.RankInfo prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code protobufUtils.PGRequest.RankInfo}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:protobufUtils.PGRequest.RankInfo)
          protobufUtils.ProtobufUtils.PGRequest.RankInfoOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return protobufUtils.ProtobufUtils.internal_static_protobufUtils_PGRequest_RankInfo_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return protobufUtils.ProtobufUtils.internal_static_protobufUtils_PGRequest_RankInfo_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  protobufUtils.ProtobufUtils.PGRequest.RankInfo.class, protobufUtils.ProtobufUtils.PGRequest.RankInfo.Builder.class);
        }

        // Construct using protobufUtils.ProtobufUtils.PGRequest.RankInfo.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          myRank_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          topUser_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          topScore_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return protobufUtils.ProtobufUtils.internal_static_protobufUtils_PGRequest_RankInfo_descriptor;
        }

        public protobufUtils.ProtobufUtils.PGRequest.RankInfo getDefaultInstanceForType() {
          return protobufUtils.ProtobufUtils.PGRequest.RankInfo.getDefaultInstance();
        }

        public protobufUtils.ProtobufUtils.PGRequest.RankInfo build() {
          protobufUtils.ProtobufUtils.PGRequest.RankInfo result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public protobufUtils.ProtobufUtils.PGRequest.RankInfo buildPartial() {
          protobufUtils.ProtobufUtils.PGRequest.RankInfo result = new protobufUtils.ProtobufUtils.PGRequest.RankInfo(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.myRank_ = myRank_;
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            topUser_ = topUser_.getUnmodifiableView();
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.topUser_ = topUser_;
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            topScore_ = topScore_.getUnmodifiableView();
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.topScore_ = topScore_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof protobufUtils.ProtobufUtils.PGRequest.RankInfo) {
            return mergeFrom((protobufUtils.ProtobufUtils.PGRequest.RankInfo)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(protobufUtils.ProtobufUtils.PGRequest.RankInfo other) {
          if (other == protobufUtils.ProtobufUtils.PGRequest.RankInfo.getDefaultInstance()) return this;
          if (other.hasMyRank()) {
            bitField0_ |= 0x00000001;
            myRank_ = other.myRank_;
            onChanged();
          }
          if (!other.topUser_.isEmpty()) {
            if (topUser_.isEmpty()) {
              topUser_ = other.topUser_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureTopUserIsMutable();
              topUser_.addAll(other.topUser_);
            }
            onChanged();
          }
          if (!other.topScore_.isEmpty()) {
            if (topScore_.isEmpty()) {
              topScore_ = other.topScore_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureTopScoreIsMutable();
              topScore_.addAll(other.topScore_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasMyRank()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          protobufUtils.ProtobufUtils.PGRequest.RankInfo parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (protobufUtils.ProtobufUtils.PGRequest.RankInfo) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object myRank_ = "";
        /**
         * <code>required string myRank = 1;</code>
         */
        public boolean hasMyRank() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string myRank = 1;</code>
         */
        public java.lang.String getMyRank() {
          java.lang.Object ref = myRank_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              myRank_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string myRank = 1;</code>
         */
        public com.google.protobuf.ByteString
            getMyRankBytes() {
          java.lang.Object ref = myRank_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            myRank_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string myRank = 1;</code>
         */
        public Builder setMyRank(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          myRank_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string myRank = 1;</code>
         */
        public Builder clearMyRank() {
          bitField0_ = (bitField0_ & ~0x00000001);
          myRank_ = getDefaultInstance().getMyRank();
          onChanged();
          return this;
        }
        /**
         * <code>required string myRank = 1;</code>
         */
        public Builder setMyRankBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          myRank_ = value;
          onChanged();
          return this;
        }

        private com.google.protobuf.LazyStringList topUser_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        private void ensureTopUserIsMutable() {
          if (!((bitField0_ & 0x00000002) == 0x00000002)) {
            topUser_ = new com.google.protobuf.LazyStringArrayList(topUser_);
            bitField0_ |= 0x00000002;
           }
        }
        /**
         * <code>repeated string topUser = 2;</code>
         */
        public com.google.protobuf.ProtocolStringList
            getTopUserList() {
          return topUser_.getUnmodifiableView();
        }
        /**
         * <code>repeated string topUser = 2;</code>
         */
        public int getTopUserCount() {
          return topUser_.size();
        }
        /**
         * <code>repeated string topUser = 2;</code>
         */
        public java.lang.String getTopUser(int index) {
          return topUser_.get(index);
        }
        /**
         * <code>repeated string topUser = 2;</code>
         */
        public com.google.protobuf.ByteString
            getTopUserBytes(int index) {
          return topUser_.getByteString(index);
        }
        /**
         * <code>repeated string topUser = 2;</code>
         */
        public Builder setTopUser(
            int index, java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureTopUserIsMutable();
          topUser_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string topUser = 2;</code>
         */
        public Builder addTopUser(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureTopUserIsMutable();
          topUser_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string topUser = 2;</code>
         */
        public Builder addAllTopUser(
            java.lang.Iterable<java.lang.String> values) {
          ensureTopUserIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, topUser_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string topUser = 2;</code>
         */
        public Builder clearTopUser() {
          topUser_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string topUser = 2;</code>
         */
        public Builder addTopUserBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureTopUserIsMutable();
          topUser_.add(value);
          onChanged();
          return this;
        }

        private com.google.protobuf.LazyStringList topScore_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        private void ensureTopScoreIsMutable() {
          if (!((bitField0_ & 0x00000004) == 0x00000004)) {
            topScore_ = new com.google.protobuf.LazyStringArrayList(topScore_);
            bitField0_ |= 0x00000004;
           }
        }
        /**
         * <code>repeated string topScore = 3;</code>
         */
        public com.google.protobuf.ProtocolStringList
            getTopScoreList() {
          return topScore_.getUnmodifiableView();
        }
        /**
         * <code>repeated string topScore = 3;</code>
         */
        public int getTopScoreCount() {
          return topScore_.size();
        }
        /**
         * <code>repeated string topScore = 3;</code>
         */
        public java.lang.String getTopScore(int index) {
          return topScore_.get(index);
        }
        /**
         * <code>repeated string topScore = 3;</code>
         */
        public com.google.protobuf.ByteString
            getTopScoreBytes(int index) {
          return topScore_.getByteString(index);
        }
        /**
         * <code>repeated string topScore = 3;</code>
         */
        public Builder setTopScore(
            int index, java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureTopScoreIsMutable();
          topScore_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string topScore = 3;</code>
         */
        public Builder addTopScore(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureTopScoreIsMutable();
          topScore_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string topScore = 3;</code>
         */
        public Builder addAllTopScore(
            java.lang.Iterable<java.lang.String> values) {
          ensureTopScoreIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, topScore_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string topScore = 3;</code>
         */
        public Builder clearTopScore() {
          topScore_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string topScore = 3;</code>
         */
        public Builder addTopScoreBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureTopScoreIsMutable();
          topScore_.add(value);
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:protobufUtils.PGRequest.RankInfo)
      }

      static {
        defaultInstance = new RankInfo(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:protobufUtils.PGRequest.RankInfo)
    }

    private int bitField0_;
    public static final int CODE_FIELD_NUMBER = 1;
    private java.lang.Object code_;
    /**
     * <code>required string Code = 1;</code>
     *
     * <pre>
     * for different kind of opration
     * </pre>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string Code = 1;</code>
     *
     * <pre>
     * for different kind of opration
     * </pre>
     */
    public java.lang.String getCode() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          code_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string Code = 1;</code>
     *
     * <pre>
     * for different kind of opration
     * </pre>
     */
    public com.google.protobuf.ByteString
        getCodeBytes() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERRORINFO_FIELD_NUMBER = 2;
    private java.lang.Object errorInfo_;
    /**
     * <code>optional string errorInfo = 2;</code>
     *
     * <pre>
     * "succed" for a successful post or get, other word for an error 
     * </pre>
     */
    public boolean hasErrorInfo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string errorInfo = 2;</code>
     *
     * <pre>
     * "succed" for a successful post or get, other word for an error 
     * </pre>
     */
    public java.lang.String getErrorInfo() {
      java.lang.Object ref = errorInfo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errorInfo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string errorInfo = 2;</code>
     *
     * <pre>
     * "succed" for a successful post or get, other word for an error 
     * </pre>
     */
    public com.google.protobuf.ByteString
        getErrorInfoBytes() {
      java.lang.Object ref = errorInfo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERNAME_FIELD_NUMBER = 3;
    private java.lang.Object username_;
    /**
     * <code>optional string username = 3;</code>
     */
    public boolean hasUsername() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string username = 3;</code>
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          username_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string username = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 4;
    private java.lang.Object password_;
    /**
     * <code>optional string password = 4;</code>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string password = 4;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string password = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SCORE_FIELD_NUMBER = 5;
    private java.lang.Object score_;
    /**
     * <code>optional string score = 5;</code>
     */
    public boolean hasScore() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string score = 5;</code>
     */
    public java.lang.String getScore() {
      java.lang.Object ref = score_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          score_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string score = 5;</code>
     */
    public com.google.protobuf.ByteString
        getScoreBytes() {
      java.lang.Object ref = score_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        score_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PICTURES_FIELD_NUMBER = 6;
    private com.google.protobuf.LazyStringList pictures_;
    /**
     * <code>repeated string pictures = 6;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getPicturesList() {
      return pictures_;
    }
    /**
     * <code>repeated string pictures = 6;</code>
     */
    public int getPicturesCount() {
      return pictures_.size();
    }
    /**
     * <code>repeated string pictures = 6;</code>
     */
    public java.lang.String getPictures(int index) {
      return pictures_.get(index);
    }
    /**
     * <code>repeated string pictures = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPicturesBytes(int index) {
      return pictures_.getByteString(index);
    }

    public static final int PICTURESID_FIELD_NUMBER = 7;
    private com.google.protobuf.LazyStringList picturesID_;
    /**
     * <code>repeated string picturesID = 7;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getPicturesIDList() {
      return picturesID_;
    }
    /**
     * <code>repeated string picturesID = 7;</code>
     */
    public int getPicturesIDCount() {
      return picturesID_.size();
    }
    /**
     * <code>repeated string picturesID = 7;</code>
     */
    public java.lang.String getPicturesID(int index) {
      return picturesID_.get(index);
    }
    /**
     * <code>repeated string picturesID = 7;</code>
     */
    public com.google.protobuf.ByteString
        getPicturesIDBytes(int index) {
      return picturesID_.getByteString(index);
    }

    public static final int RANKINFO_FIELD_NUMBER = 8;
    private protobufUtils.ProtobufUtils.PGRequest.RankInfo rankInfo_;
    /**
     * <code>optional .protobufUtils.PGRequest.RankInfo rankInfo = 8;</code>
     */
    public boolean hasRankInfo() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional .protobufUtils.PGRequest.RankInfo rankInfo = 8;</code>
     */
    public protobufUtils.ProtobufUtils.PGRequest.RankInfo getRankInfo() {
      return rankInfo_;
    }
    /**
     * <code>optional .protobufUtils.PGRequest.RankInfo rankInfo = 8;</code>
     */
    public protobufUtils.ProtobufUtils.PGRequest.RankInfoOrBuilder getRankInfoOrBuilder() {
      return rankInfo_;
    }

    public static final int NICKNAME_FIELD_NUMBER = 9;
    private java.lang.Object nickname_;
    /**
     * <code>optional string nickname = 9;</code>
     */
    public boolean hasNickname() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string nickname = 9;</code>
     */
    public java.lang.String getNickname() {
      java.lang.Object ref = nickname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nickname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string nickname = 9;</code>
     */
    public com.google.protobuf.ByteString
        getNicknameBytes() {
      java.lang.Object ref = nickname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      code_ = "";
      errorInfo_ = "";
      username_ = "";
      password_ = "";
      score_ = "";
      pictures_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      picturesID_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      rankInfo_ = protobufUtils.ProtobufUtils.PGRequest.RankInfo.getDefaultInstance();
      nickname_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasRankInfo()) {
        if (!getRankInfo().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getCodeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getErrorInfoBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getScoreBytes());
      }
      for (int i = 0; i < pictures_.size(); i++) {
        output.writeBytes(6, pictures_.getByteString(i));
      }
      for (int i = 0; i < picturesID_.size(); i++) {
        output.writeBytes(7, picturesID_.getByteString(i));
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeMessage(8, rankInfo_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(9, getNicknameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getCodeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getErrorInfoBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getScoreBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < pictures_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(pictures_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getPicturesList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < picturesID_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(picturesID_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getPicturesIDList().size();
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, rankInfo_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getNicknameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobufUtils.ProtobufUtils.PGRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobufUtils.ProtobufUtils.PGRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobufUtils.ProtobufUtils.PGRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobufUtils.ProtobufUtils.PGRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobufUtils.ProtobufUtils.PGRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobufUtils.ProtobufUtils.PGRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobufUtils.ProtobufUtils.PGRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobufUtils.ProtobufUtils.PGRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobufUtils.ProtobufUtils.PGRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobufUtils.ProtobufUtils.PGRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobufUtils.ProtobufUtils.PGRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobufUtils.PGRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobufUtils.PGRequest)
        protobufUtils.ProtobufUtils.PGRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobufUtils.ProtobufUtils.internal_static_protobufUtils_PGRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobufUtils.ProtobufUtils.internal_static_protobufUtils_PGRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobufUtils.ProtobufUtils.PGRequest.class, protobufUtils.ProtobufUtils.PGRequest.Builder.class);
      }

      // Construct using protobufUtils.ProtobufUtils.PGRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRankInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        code_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        errorInfo_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        username_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        score_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        pictures_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        picturesID_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        if (rankInfoBuilder_ == null) {
          rankInfo_ = protobufUtils.ProtobufUtils.PGRequest.RankInfo.getDefaultInstance();
        } else {
          rankInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        nickname_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobufUtils.ProtobufUtils.internal_static_protobufUtils_PGRequest_descriptor;
      }

      public protobufUtils.ProtobufUtils.PGRequest getDefaultInstanceForType() {
        return protobufUtils.ProtobufUtils.PGRequest.getDefaultInstance();
      }

      public protobufUtils.ProtobufUtils.PGRequest build() {
        protobufUtils.ProtobufUtils.PGRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobufUtils.ProtobufUtils.PGRequest buildPartial() {
        protobufUtils.ProtobufUtils.PGRequest result = new protobufUtils.ProtobufUtils.PGRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.code_ = code_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.errorInfo_ = errorInfo_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.username_ = username_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.password_ = password_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.score_ = score_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          pictures_ = pictures_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.pictures_ = pictures_;
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          picturesID_ = picturesID_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.picturesID_ = picturesID_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000020;
        }
        if (rankInfoBuilder_ == null) {
          result.rankInfo_ = rankInfo_;
        } else {
          result.rankInfo_ = rankInfoBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000040;
        }
        result.nickname_ = nickname_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobufUtils.ProtobufUtils.PGRequest) {
          return mergeFrom((protobufUtils.ProtobufUtils.PGRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobufUtils.ProtobufUtils.PGRequest other) {
        if (other == protobufUtils.ProtobufUtils.PGRequest.getDefaultInstance()) return this;
        if (other.hasCode()) {
          bitField0_ |= 0x00000001;
          code_ = other.code_;
          onChanged();
        }
        if (other.hasErrorInfo()) {
          bitField0_ |= 0x00000002;
          errorInfo_ = other.errorInfo_;
          onChanged();
        }
        if (other.hasUsername()) {
          bitField0_ |= 0x00000004;
          username_ = other.username_;
          onChanged();
        }
        if (other.hasPassword()) {
          bitField0_ |= 0x00000008;
          password_ = other.password_;
          onChanged();
        }
        if (other.hasScore()) {
          bitField0_ |= 0x00000010;
          score_ = other.score_;
          onChanged();
        }
        if (!other.pictures_.isEmpty()) {
          if (pictures_.isEmpty()) {
            pictures_ = other.pictures_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensurePicturesIsMutable();
            pictures_.addAll(other.pictures_);
          }
          onChanged();
        }
        if (!other.picturesID_.isEmpty()) {
          if (picturesID_.isEmpty()) {
            picturesID_ = other.picturesID_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensurePicturesIDIsMutable();
            picturesID_.addAll(other.picturesID_);
          }
          onChanged();
        }
        if (other.hasRankInfo()) {
          mergeRankInfo(other.getRankInfo());
        }
        if (other.hasNickname()) {
          bitField0_ |= 0x00000100;
          nickname_ = other.nickname_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCode()) {
          
          return false;
        }
        if (hasRankInfo()) {
          if (!getRankInfo().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobufUtils.ProtobufUtils.PGRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobufUtils.ProtobufUtils.PGRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object code_ = "";
      /**
       * <code>required string Code = 1;</code>
       *
       * <pre>
       * for different kind of opration
       * </pre>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string Code = 1;</code>
       *
       * <pre>
       * for different kind of opration
       * </pre>
       */
      public java.lang.String getCode() {
        java.lang.Object ref = code_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            code_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string Code = 1;</code>
       *
       * <pre>
       * for different kind of opration
       * </pre>
       */
      public com.google.protobuf.ByteString
          getCodeBytes() {
        java.lang.Object ref = code_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          code_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string Code = 1;</code>
       *
       * <pre>
       * for different kind of opration
       * </pre>
       */
      public Builder setCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string Code = 1;</code>
       *
       * <pre>
       * for different kind of opration
       * </pre>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = getDefaultInstance().getCode();
        onChanged();
        return this;
      }
      /**
       * <code>required string Code = 1;</code>
       *
       * <pre>
       * for different kind of opration
       * </pre>
       */
      public Builder setCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        code_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object errorInfo_ = "";
      /**
       * <code>optional string errorInfo = 2;</code>
       *
       * <pre>
       * "succed" for a successful post or get, other word for an error 
       * </pre>
       */
      public boolean hasErrorInfo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string errorInfo = 2;</code>
       *
       * <pre>
       * "succed" for a successful post or get, other word for an error 
       * </pre>
       */
      public java.lang.String getErrorInfo() {
        java.lang.Object ref = errorInfo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            errorInfo_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string errorInfo = 2;</code>
       *
       * <pre>
       * "succed" for a successful post or get, other word for an error 
       * </pre>
       */
      public com.google.protobuf.ByteString
          getErrorInfoBytes() {
        java.lang.Object ref = errorInfo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorInfo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string errorInfo = 2;</code>
       *
       * <pre>
       * "succed" for a successful post or get, other word for an error 
       * </pre>
       */
      public Builder setErrorInfo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errorInfo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorInfo = 2;</code>
       *
       * <pre>
       * "succed" for a successful post or get, other word for an error 
       * </pre>
       */
      public Builder clearErrorInfo() {
        bitField0_ = (bitField0_ & ~0x00000002);
        errorInfo_ = getDefaultInstance().getErrorInfo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorInfo = 2;</code>
       *
       * <pre>
       * "succed" for a successful post or get, other word for an error 
       * </pre>
       */
      public Builder setErrorInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errorInfo_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object username_ = "";
      /**
       * <code>optional string username = 3;</code>
       */
      public boolean hasUsername() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string username = 3;</code>
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            username_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string username = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string username = 3;</code>
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        username_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string username = 3;</code>
       */
      public Builder clearUsername() {
        bitField0_ = (bitField0_ & ~0x00000004);
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      /**
       * <code>optional string username = 3;</code>
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        username_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>optional string password = 4;</code>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string password = 4;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            password_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string password = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string password = 4;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 4;</code>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000008);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 4;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        password_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object score_ = "";
      /**
       * <code>optional string score = 5;</code>
       */
      public boolean hasScore() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string score = 5;</code>
       */
      public java.lang.String getScore() {
        java.lang.Object ref = score_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            score_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string score = 5;</code>
       */
      public com.google.protobuf.ByteString
          getScoreBytes() {
        java.lang.Object ref = score_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          score_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string score = 5;</code>
       */
      public Builder setScore(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        score_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string score = 5;</code>
       */
      public Builder clearScore() {
        bitField0_ = (bitField0_ & ~0x00000010);
        score_ = getDefaultInstance().getScore();
        onChanged();
        return this;
      }
      /**
       * <code>optional string score = 5;</code>
       */
      public Builder setScoreBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        score_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList pictures_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePicturesIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          pictures_ = new com.google.protobuf.LazyStringArrayList(pictures_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated string pictures = 6;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getPicturesList() {
        return pictures_.getUnmodifiableView();
      }
      /**
       * <code>repeated string pictures = 6;</code>
       */
      public int getPicturesCount() {
        return pictures_.size();
      }
      /**
       * <code>repeated string pictures = 6;</code>
       */
      public java.lang.String getPictures(int index) {
        return pictures_.get(index);
      }
      /**
       * <code>repeated string pictures = 6;</code>
       */
      public com.google.protobuf.ByteString
          getPicturesBytes(int index) {
        return pictures_.getByteString(index);
      }
      /**
       * <code>repeated string pictures = 6;</code>
       */
      public Builder setPictures(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePicturesIsMutable();
        pictures_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string pictures = 6;</code>
       */
      public Builder addPictures(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePicturesIsMutable();
        pictures_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string pictures = 6;</code>
       */
      public Builder addAllPictures(
          java.lang.Iterable<java.lang.String> values) {
        ensurePicturesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, pictures_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string pictures = 6;</code>
       */
      public Builder clearPictures() {
        pictures_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string pictures = 6;</code>
       */
      public Builder addPicturesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePicturesIsMutable();
        pictures_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList picturesID_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePicturesIDIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          picturesID_ = new com.google.protobuf.LazyStringArrayList(picturesID_);
          bitField0_ |= 0x00000040;
         }
      }
      /**
       * <code>repeated string picturesID = 7;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getPicturesIDList() {
        return picturesID_.getUnmodifiableView();
      }
      /**
       * <code>repeated string picturesID = 7;</code>
       */
      public int getPicturesIDCount() {
        return picturesID_.size();
      }
      /**
       * <code>repeated string picturesID = 7;</code>
       */
      public java.lang.String getPicturesID(int index) {
        return picturesID_.get(index);
      }
      /**
       * <code>repeated string picturesID = 7;</code>
       */
      public com.google.protobuf.ByteString
          getPicturesIDBytes(int index) {
        return picturesID_.getByteString(index);
      }
      /**
       * <code>repeated string picturesID = 7;</code>
       */
      public Builder setPicturesID(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePicturesIDIsMutable();
        picturesID_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string picturesID = 7;</code>
       */
      public Builder addPicturesID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePicturesIDIsMutable();
        picturesID_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string picturesID = 7;</code>
       */
      public Builder addAllPicturesID(
          java.lang.Iterable<java.lang.String> values) {
        ensurePicturesIDIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, picturesID_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string picturesID = 7;</code>
       */
      public Builder clearPicturesID() {
        picturesID_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string picturesID = 7;</code>
       */
      public Builder addPicturesIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePicturesIDIsMutable();
        picturesID_.add(value);
        onChanged();
        return this;
      }

      private protobufUtils.ProtobufUtils.PGRequest.RankInfo rankInfo_ = protobufUtils.ProtobufUtils.PGRequest.RankInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          protobufUtils.ProtobufUtils.PGRequest.RankInfo, protobufUtils.ProtobufUtils.PGRequest.RankInfo.Builder, protobufUtils.ProtobufUtils.PGRequest.RankInfoOrBuilder> rankInfoBuilder_;
      /**
       * <code>optional .protobufUtils.PGRequest.RankInfo rankInfo = 8;</code>
       */
      public boolean hasRankInfo() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional .protobufUtils.PGRequest.RankInfo rankInfo = 8;</code>
       */
      public protobufUtils.ProtobufUtils.PGRequest.RankInfo getRankInfo() {
        if (rankInfoBuilder_ == null) {
          return rankInfo_;
        } else {
          return rankInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .protobufUtils.PGRequest.RankInfo rankInfo = 8;</code>
       */
      public Builder setRankInfo(protobufUtils.ProtobufUtils.PGRequest.RankInfo value) {
        if (rankInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          rankInfo_ = value;
          onChanged();
        } else {
          rankInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .protobufUtils.PGRequest.RankInfo rankInfo = 8;</code>
       */
      public Builder setRankInfo(
          protobufUtils.ProtobufUtils.PGRequest.RankInfo.Builder builderForValue) {
        if (rankInfoBuilder_ == null) {
          rankInfo_ = builderForValue.build();
          onChanged();
        } else {
          rankInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .protobufUtils.PGRequest.RankInfo rankInfo = 8;</code>
       */
      public Builder mergeRankInfo(protobufUtils.ProtobufUtils.PGRequest.RankInfo value) {
        if (rankInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000080) == 0x00000080) &&
              rankInfo_ != protobufUtils.ProtobufUtils.PGRequest.RankInfo.getDefaultInstance()) {
            rankInfo_ =
              protobufUtils.ProtobufUtils.PGRequest.RankInfo.newBuilder(rankInfo_).mergeFrom(value).buildPartial();
          } else {
            rankInfo_ = value;
          }
          onChanged();
        } else {
          rankInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .protobufUtils.PGRequest.RankInfo rankInfo = 8;</code>
       */
      public Builder clearRankInfo() {
        if (rankInfoBuilder_ == null) {
          rankInfo_ = protobufUtils.ProtobufUtils.PGRequest.RankInfo.getDefaultInstance();
          onChanged();
        } else {
          rankInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      /**
       * <code>optional .protobufUtils.PGRequest.RankInfo rankInfo = 8;</code>
       */
      public protobufUtils.ProtobufUtils.PGRequest.RankInfo.Builder getRankInfoBuilder() {
        bitField0_ |= 0x00000080;
        onChanged();
        return getRankInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .protobufUtils.PGRequest.RankInfo rankInfo = 8;</code>
       */
      public protobufUtils.ProtobufUtils.PGRequest.RankInfoOrBuilder getRankInfoOrBuilder() {
        if (rankInfoBuilder_ != null) {
          return rankInfoBuilder_.getMessageOrBuilder();
        } else {
          return rankInfo_;
        }
      }
      /**
       * <code>optional .protobufUtils.PGRequest.RankInfo rankInfo = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          protobufUtils.ProtobufUtils.PGRequest.RankInfo, protobufUtils.ProtobufUtils.PGRequest.RankInfo.Builder, protobufUtils.ProtobufUtils.PGRequest.RankInfoOrBuilder> 
          getRankInfoFieldBuilder() {
        if (rankInfoBuilder_ == null) {
          rankInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              protobufUtils.ProtobufUtils.PGRequest.RankInfo, protobufUtils.ProtobufUtils.PGRequest.RankInfo.Builder, protobufUtils.ProtobufUtils.PGRequest.RankInfoOrBuilder>(
                  getRankInfo(),
                  getParentForChildren(),
                  isClean());
          rankInfo_ = null;
        }
        return rankInfoBuilder_;
      }

      private java.lang.Object nickname_ = "";
      /**
       * <code>optional string nickname = 9;</code>
       */
      public boolean hasNickname() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string nickname = 9;</code>
       */
      public java.lang.String getNickname() {
        java.lang.Object ref = nickname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            nickname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string nickname = 9;</code>
       */
      public com.google.protobuf.ByteString
          getNicknameBytes() {
        java.lang.Object ref = nickname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nickname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string nickname = 9;</code>
       */
      public Builder setNickname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        nickname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string nickname = 9;</code>
       */
      public Builder clearNickname() {
        bitField0_ = (bitField0_ & ~0x00000100);
        nickname_ = getDefaultInstance().getNickname();
        onChanged();
        return this;
      }
      /**
       * <code>optional string nickname = 9;</code>
       */
      public Builder setNicknameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        nickname_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobufUtils.PGRequest)
    }

    static {
      defaultInstance = new PGRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobufUtils.PGRequest)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobufUtils_PGRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobufUtils_PGRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobufUtils_PGRequest_RankInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobufUtils_PGRequest_RankInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023protobufUtils.proto\022\rprotobufUtils\"\213\002\n" +
      "\tPGRequest\022\014\n\004Code\030\001 \002(\t\022\021\n\terrorInfo\030\002 " +
      "\001(\t\022\020\n\010username\030\003 \001(\t\022\020\n\010password\030\004 \001(\t\022" +
      "\r\n\005score\030\005 \001(\t\022\020\n\010pictures\030\006 \003(\t\022\022\n\npict" +
      "uresID\030\007 \003(\t\0223\n\010rankInfo\030\010 \001(\0132!.protobu" +
      "fUtils.PGRequest.RankInfo\022\020\n\010nickname\030\t " +
      "\001(\t\032=\n\010RankInfo\022\016\n\006myRank\030\001 \002(\t\022\017\n\007topUs" +
      "er\030\002 \003(\t\022\020\n\010topScore\030\003 \003(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobufUtils_PGRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobufUtils_PGRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobufUtils_PGRequest_descriptor,
        new java.lang.String[] { "Code", "ErrorInfo", "Username", "Password", "Score", "Pictures", "PicturesID", "RankInfo", "Nickname", });
    internal_static_protobufUtils_PGRequest_RankInfo_descriptor =
      internal_static_protobufUtils_PGRequest_descriptor.getNestedTypes().get(0);
    internal_static_protobufUtils_PGRequest_RankInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobufUtils_PGRequest_RankInfo_descriptor,
        new java.lang.String[] { "MyRank", "TopUser", "TopScore", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
