// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobufUtils.proto

package protobufUtils;

public final class ProtobufUtils {
  private ProtobufUtils() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PGRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobufUtils.PGRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string requestType = 1;</code>
     *
     * <pre>
     * with values "post" and "get"
     * </pre>
     */
    boolean hasRequestType();
    /**
     * <code>required string requestType = 1;</code>
     *
     * <pre>
     * with values "post" and "get"
     * </pre>
     */
    java.lang.String getRequestType();
    /**
     * <code>required string requestType = 1;</code>
     *
     * <pre>
     * with values "post" and "get"
     * </pre>
     */
    com.google.protobuf.ByteString
        getRequestTypeBytes();

    /**
     * <code>required string requestCode = 2;</code>
     *
     * <pre>
     * for different kind of infomation
     * </pre>
     */
    boolean hasRequestCode();
    /**
     * <code>required string requestCode = 2;</code>
     *
     * <pre>
     * for different kind of infomation
     * </pre>
     */
    java.lang.String getRequestCode();
    /**
     * <code>required string requestCode = 2;</code>
     *
     * <pre>
     * for different kind of infomation
     * </pre>
     */
    com.google.protobuf.ByteString
        getRequestCodeBytes();

    /**
     * <code>optional string username = 3;</code>
     *
     * <pre>
     * field for type "post"
     * </pre>
     */
    boolean hasUsername();
    /**
     * <code>optional string username = 3;</code>
     *
     * <pre>
     * field for type "post"
     * </pre>
     */
    java.lang.String getUsername();
    /**
     * <code>optional string username = 3;</code>
     *
     * <pre>
     * field for type "post"
     * </pre>
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    /**
     * <code>optional string password = 4;</code>
     */
    boolean hasPassword();
    /**
     * <code>optional string password = 4;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>optional string password = 4;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <code>optional string score = 5;</code>
     */
    boolean hasScore();
    /**
     * <code>optional string score = 5;</code>
     */
    java.lang.String getScore();
    /**
     * <code>optional string score = 5;</code>
     */
    com.google.protobuf.ByteString
        getScoreBytes();

    /**
     * <code>optional string picture = 6;</code>
     */
    boolean hasPicture();
    /**
     * <code>optional string picture = 6;</code>
     */
    java.lang.String getPicture();
    /**
     * <code>optional string picture = 6;</code>
     */
    com.google.protobuf.ByteString
        getPictureBytes();

    /**
     * <code>repeated string picList = 7;</code>
     */
    com.google.protobuf.ProtocolStringList
        getPicListList();
    /**
     * <code>repeated string picList = 7;</code>
     */
    int getPicListCount();
    /**
     * <code>repeated string picList = 7;</code>
     */
    java.lang.String getPicList(int index);
    /**
     * <code>repeated string picList = 7;</code>
     */
    com.google.protobuf.ByteString
        getPicListBytes(int index);

    /**
     * <code>optional .protobufUtils.PGRequest.RankInfo rankInfo = 8;</code>
     */
    boolean hasRankInfo();
    /**
     * <code>optional .protobufUtils.PGRequest.RankInfo rankInfo = 8;</code>
     */
    protobufUtils.ProtobufUtils.PGRequest.RankInfo getRankInfo();
    /**
     * <code>optional .protobufUtils.PGRequest.RankInfo rankInfo = 8;</code>
     */
    protobufUtils.ProtobufUtils.PGRequest.RankInfoOrBuilder getRankInfoOrBuilder();
  }
  /**
   * Protobuf type {@code protobufUtils.PGRequest}
   */
  public static final class PGRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobufUtils.PGRequest)
      PGRequestOrBuilder {
    // Use PGRequest.newBuilder() to construct.
    private PGRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PGRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PGRequest defaultInstance;
    public static PGRequest getDefaultInstance() {
      return defaultInstance;
    }

    public PGRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PGRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              requestType_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              requestCode_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              username_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              password_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              score_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              picture_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                picList_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000040;
              }
              picList_.add(bs);
              break;
            }
            case 66: {
              protobufUtils.ProtobufUtils.PGRequest.RankInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000040) == 0x00000040)) {
                subBuilder = rankInfo_.toBuilder();
              }
              rankInfo_ = input.readMessage(protobufUtils.ProtobufUtils.PGRequest.RankInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(rankInfo_);
                rankInfo_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000040;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          picList_ = picList_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobufUtils.ProtobufUtils.internal_static_protobufUtils_PGRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobufUtils.ProtobufUtils.internal_static_protobufUtils_PGRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobufUtils.ProtobufUtils.PGRequest.class, protobufUtils.ProtobufUtils.PGRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<PGRequest> PARSER =
        new com.google.protobuf.AbstractParser<PGRequest>() {
      public PGRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PGRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PGRequest> getParserForType() {
      return PARSER;
    }

    public interface RankInfoOrBuilder extends
        // @@protoc_insertion_point(interface_extends:protobufUtils.PGRequest.RankInfo)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string myRank = 1;</code>
       */
      boolean hasMyRank();
      /**
       * <code>required string myRank = 1;</code>
       */
      java.lang.String getMyRank();
      /**
       * <code>required string myRank = 1;</code>
       */
      com.google.protobuf.ByteString
          getMyRankBytes();

      /**
       * <code>repeated string username = 2;</code>
       */
      com.google.protobuf.ProtocolStringList
          getUsernameList();
      /**
       * <code>repeated string username = 2;</code>
       */
      int getUsernameCount();
      /**
       * <code>repeated string username = 2;</code>
       */
      java.lang.String getUsername(int index);
      /**
       * <code>repeated string username = 2;</code>
       */
      com.google.protobuf.ByteString
          getUsernameBytes(int index);
    }
    /**
     * Protobuf type {@code protobufUtils.PGRequest.RankInfo}
     *
     * <pre>
     * field for type "get"
     * </pre>
     */
    public static final class RankInfo extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:protobufUtils.PGRequest.RankInfo)
        RankInfoOrBuilder {
      // Use RankInfo.newBuilder() to construct.
      private RankInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private RankInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final RankInfo defaultInstance;
      public static RankInfo getDefaultInstance() {
        return defaultInstance;
      }

      public RankInfo getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private RankInfo(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                myRank_ = bs;
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                  username_ = new com.google.protobuf.LazyStringArrayList();
                  mutable_bitField0_ |= 0x00000002;
                }
                username_.add(bs);
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
            username_ = username_.getUnmodifiableView();
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobufUtils.ProtobufUtils.internal_static_protobufUtils_PGRequest_RankInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobufUtils.ProtobufUtils.internal_static_protobufUtils_PGRequest_RankInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobufUtils.ProtobufUtils.PGRequest.RankInfo.class, protobufUtils.ProtobufUtils.PGRequest.RankInfo.Builder.class);
      }

      public static com.google.protobuf.Parser<RankInfo> PARSER =
          new com.google.protobuf.AbstractParser<RankInfo>() {
        public RankInfo parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new RankInfo(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<RankInfo> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int MYRANK_FIELD_NUMBER = 1;
      private java.lang.Object myRank_;
      /**
       * <code>required string myRank = 1;</code>
       */
      public boolean hasMyRank() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string myRank = 1;</code>
       */
      public java.lang.String getMyRank() {
        java.lang.Object ref = myRank_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            myRank_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string myRank = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMyRankBytes() {
        java.lang.Object ref = myRank_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          myRank_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int USERNAME_FIELD_NUMBER = 2;
      private com.google.protobuf.LazyStringList username_;
      /**
       * <code>repeated string username = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getUsernameList() {
        return username_;
      }
      /**
       * <code>repeated string username = 2;</code>
       */
      public int getUsernameCount() {
        return username_.size();
      }
      /**
       * <code>repeated string username = 2;</code>
       */
      public java.lang.String getUsername(int index) {
        return username_.get(index);
      }
      /**
       * <code>repeated string username = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes(int index) {
        return username_.getByteString(index);
      }

      private void initFields() {
        myRank_ = "";
        username_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasMyRank()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getMyRankBytes());
        }
        for (int i = 0; i < username_.size(); i++) {
          output.writeBytes(2, username_.getByteString(i));
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getMyRankBytes());
        }
        {
          int dataSize = 0;
          for (int i = 0; i < username_.size(); i++) {
            dataSize += com.google.protobuf.CodedOutputStream
              .computeBytesSizeNoTag(username_.getByteString(i));
          }
          size += dataSize;
          size += 1 * getUsernameList().size();
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static protobufUtils.ProtobufUtils.PGRequest.RankInfo parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static protobufUtils.ProtobufUtils.PGRequest.RankInfo parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static protobufUtils.ProtobufUtils.PGRequest.RankInfo parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static protobufUtils.ProtobufUtils.PGRequest.RankInfo parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static protobufUtils.ProtobufUtils.PGRequest.RankInfo parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static protobufUtils.ProtobufUtils.PGRequest.RankInfo parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static protobufUtils.ProtobufUtils.PGRequest.RankInfo parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static protobufUtils.ProtobufUtils.PGRequest.RankInfo parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static protobufUtils.ProtobufUtils.PGRequest.RankInfo parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static protobufUtils.ProtobufUtils.PGRequest.RankInfo parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(protobufUtils.ProtobufUtils.PGRequest.RankInfo prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code protobufUtils.PGRequest.RankInfo}
       *
       * <pre>
       * field for type "get"
       * </pre>
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:protobufUtils.PGRequest.RankInfo)
          protobufUtils.ProtobufUtils.PGRequest.RankInfoOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return protobufUtils.ProtobufUtils.internal_static_protobufUtils_PGRequest_RankInfo_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return protobufUtils.ProtobufUtils.internal_static_protobufUtils_PGRequest_RankInfo_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  protobufUtils.ProtobufUtils.PGRequest.RankInfo.class, protobufUtils.ProtobufUtils.PGRequest.RankInfo.Builder.class);
        }

        // Construct using protobufUtils.ProtobufUtils.PGRequest.RankInfo.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          myRank_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          username_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return protobufUtils.ProtobufUtils.internal_static_protobufUtils_PGRequest_RankInfo_descriptor;
        }

        public protobufUtils.ProtobufUtils.PGRequest.RankInfo getDefaultInstanceForType() {
          return protobufUtils.ProtobufUtils.PGRequest.RankInfo.getDefaultInstance();
        }

        public protobufUtils.ProtobufUtils.PGRequest.RankInfo build() {
          protobufUtils.ProtobufUtils.PGRequest.RankInfo result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public protobufUtils.ProtobufUtils.PGRequest.RankInfo buildPartial() {
          protobufUtils.ProtobufUtils.PGRequest.RankInfo result = new protobufUtils.ProtobufUtils.PGRequest.RankInfo(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.myRank_ = myRank_;
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            username_ = username_.getUnmodifiableView();
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.username_ = username_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof protobufUtils.ProtobufUtils.PGRequest.RankInfo) {
            return mergeFrom((protobufUtils.ProtobufUtils.PGRequest.RankInfo)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(protobufUtils.ProtobufUtils.PGRequest.RankInfo other) {
          if (other == protobufUtils.ProtobufUtils.PGRequest.RankInfo.getDefaultInstance()) return this;
          if (other.hasMyRank()) {
            bitField0_ |= 0x00000001;
            myRank_ = other.myRank_;
            onChanged();
          }
          if (!other.username_.isEmpty()) {
            if (username_.isEmpty()) {
              username_ = other.username_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureUsernameIsMutable();
              username_.addAll(other.username_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasMyRank()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          protobufUtils.ProtobufUtils.PGRequest.RankInfo parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (protobufUtils.ProtobufUtils.PGRequest.RankInfo) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object myRank_ = "";
        /**
         * <code>required string myRank = 1;</code>
         */
        public boolean hasMyRank() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string myRank = 1;</code>
         */
        public java.lang.String getMyRank() {
          java.lang.Object ref = myRank_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              myRank_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string myRank = 1;</code>
         */
        public com.google.protobuf.ByteString
            getMyRankBytes() {
          java.lang.Object ref = myRank_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            myRank_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string myRank = 1;</code>
         */
        public Builder setMyRank(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          myRank_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string myRank = 1;</code>
         */
        public Builder clearMyRank() {
          bitField0_ = (bitField0_ & ~0x00000001);
          myRank_ = getDefaultInstance().getMyRank();
          onChanged();
          return this;
        }
        /**
         * <code>required string myRank = 1;</code>
         */
        public Builder setMyRankBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          myRank_ = value;
          onChanged();
          return this;
        }

        private com.google.protobuf.LazyStringList username_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        private void ensureUsernameIsMutable() {
          if (!((bitField0_ & 0x00000002) == 0x00000002)) {
            username_ = new com.google.protobuf.LazyStringArrayList(username_);
            bitField0_ |= 0x00000002;
           }
        }
        /**
         * <code>repeated string username = 2;</code>
         */
        public com.google.protobuf.ProtocolStringList
            getUsernameList() {
          return username_.getUnmodifiableView();
        }
        /**
         * <code>repeated string username = 2;</code>
         */
        public int getUsernameCount() {
          return username_.size();
        }
        /**
         * <code>repeated string username = 2;</code>
         */
        public java.lang.String getUsername(int index) {
          return username_.get(index);
        }
        /**
         * <code>repeated string username = 2;</code>
         */
        public com.google.protobuf.ByteString
            getUsernameBytes(int index) {
          return username_.getByteString(index);
        }
        /**
         * <code>repeated string username = 2;</code>
         */
        public Builder setUsername(
            int index, java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureUsernameIsMutable();
          username_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string username = 2;</code>
         */
        public Builder addUsername(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureUsernameIsMutable();
          username_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string username = 2;</code>
         */
        public Builder addAllUsername(
            java.lang.Iterable<java.lang.String> values) {
          ensureUsernameIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, username_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string username = 2;</code>
         */
        public Builder clearUsername() {
          username_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string username = 2;</code>
         */
        public Builder addUsernameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureUsernameIsMutable();
          username_.add(value);
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:protobufUtils.PGRequest.RankInfo)
      }

      static {
        defaultInstance = new RankInfo(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:protobufUtils.PGRequest.RankInfo)
    }

    private int bitField0_;
    public static final int REQUESTTYPE_FIELD_NUMBER = 1;
    private java.lang.Object requestType_;
    /**
     * <code>required string requestType = 1;</code>
     *
     * <pre>
     * with values "post" and "get"
     * </pre>
     */
    public boolean hasRequestType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string requestType = 1;</code>
     *
     * <pre>
     * with values "post" and "get"
     * </pre>
     */
    public java.lang.String getRequestType() {
      java.lang.Object ref = requestType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          requestType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string requestType = 1;</code>
     *
     * <pre>
     * with values "post" and "get"
     * </pre>
     */
    public com.google.protobuf.ByteString
        getRequestTypeBytes() {
      java.lang.Object ref = requestType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQUESTCODE_FIELD_NUMBER = 2;
    private java.lang.Object requestCode_;
    /**
     * <code>required string requestCode = 2;</code>
     *
     * <pre>
     * for different kind of infomation
     * </pre>
     */
    public boolean hasRequestCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string requestCode = 2;</code>
     *
     * <pre>
     * for different kind of infomation
     * </pre>
     */
    public java.lang.String getRequestCode() {
      java.lang.Object ref = requestCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          requestCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string requestCode = 2;</code>
     *
     * <pre>
     * for different kind of infomation
     * </pre>
     */
    public com.google.protobuf.ByteString
        getRequestCodeBytes() {
      java.lang.Object ref = requestCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERNAME_FIELD_NUMBER = 3;
    private java.lang.Object username_;
    /**
     * <code>optional string username = 3;</code>
     *
     * <pre>
     * field for type "post"
     * </pre>
     */
    public boolean hasUsername() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string username = 3;</code>
     *
     * <pre>
     * field for type "post"
     * </pre>
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          username_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string username = 3;</code>
     *
     * <pre>
     * field for type "post"
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 4;
    private java.lang.Object password_;
    /**
     * <code>optional string password = 4;</code>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string password = 4;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string password = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SCORE_FIELD_NUMBER = 5;
    private java.lang.Object score_;
    /**
     * <code>optional string score = 5;</code>
     */
    public boolean hasScore() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string score = 5;</code>
     */
    public java.lang.String getScore() {
      java.lang.Object ref = score_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          score_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string score = 5;</code>
     */
    public com.google.protobuf.ByteString
        getScoreBytes() {
      java.lang.Object ref = score_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        score_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PICTURE_FIELD_NUMBER = 6;
    private java.lang.Object picture_;
    /**
     * <code>optional string picture = 6;</code>
     */
    public boolean hasPicture() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string picture = 6;</code>
     */
    public java.lang.String getPicture() {
      java.lang.Object ref = picture_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          picture_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string picture = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPictureBytes() {
      java.lang.Object ref = picture_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        picture_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PICLIST_FIELD_NUMBER = 7;
    private com.google.protobuf.LazyStringList picList_;
    /**
     * <code>repeated string picList = 7;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getPicListList() {
      return picList_;
    }
    /**
     * <code>repeated string picList = 7;</code>
     */
    public int getPicListCount() {
      return picList_.size();
    }
    /**
     * <code>repeated string picList = 7;</code>
     */
    public java.lang.String getPicList(int index) {
      return picList_.get(index);
    }
    /**
     * <code>repeated string picList = 7;</code>
     */
    public com.google.protobuf.ByteString
        getPicListBytes(int index) {
      return picList_.getByteString(index);
    }

    public static final int RANKINFO_FIELD_NUMBER = 8;
    private protobufUtils.ProtobufUtils.PGRequest.RankInfo rankInfo_;
    /**
     * <code>optional .protobufUtils.PGRequest.RankInfo rankInfo = 8;</code>
     */
    public boolean hasRankInfo() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional .protobufUtils.PGRequest.RankInfo rankInfo = 8;</code>
     */
    public protobufUtils.ProtobufUtils.PGRequest.RankInfo getRankInfo() {
      return rankInfo_;
    }
    /**
     * <code>optional .protobufUtils.PGRequest.RankInfo rankInfo = 8;</code>
     */
    public protobufUtils.ProtobufUtils.PGRequest.RankInfoOrBuilder getRankInfoOrBuilder() {
      return rankInfo_;
    }

    private void initFields() {
      requestType_ = "";
      requestCode_ = "";
      username_ = "";
      password_ = "";
      score_ = "";
      picture_ = "";
      picList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      rankInfo_ = protobufUtils.ProtobufUtils.PGRequest.RankInfo.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRequestType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRequestCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasRankInfo()) {
        if (!getRankInfo().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getRequestTypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getRequestCodeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getScoreBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getPictureBytes());
      }
      for (int i = 0; i < picList_.size(); i++) {
        output.writeBytes(7, picList_.getByteString(i));
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeMessage(8, rankInfo_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getRequestTypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getRequestCodeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getScoreBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getPictureBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < picList_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(picList_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getPicListList().size();
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, rankInfo_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobufUtils.ProtobufUtils.PGRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobufUtils.ProtobufUtils.PGRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobufUtils.ProtobufUtils.PGRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobufUtils.ProtobufUtils.PGRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobufUtils.ProtobufUtils.PGRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobufUtils.ProtobufUtils.PGRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobufUtils.ProtobufUtils.PGRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobufUtils.ProtobufUtils.PGRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobufUtils.ProtobufUtils.PGRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobufUtils.ProtobufUtils.PGRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobufUtils.ProtobufUtils.PGRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobufUtils.PGRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobufUtils.PGRequest)
        protobufUtils.ProtobufUtils.PGRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobufUtils.ProtobufUtils.internal_static_protobufUtils_PGRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobufUtils.ProtobufUtils.internal_static_protobufUtils_PGRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobufUtils.ProtobufUtils.PGRequest.class, protobufUtils.ProtobufUtils.PGRequest.Builder.class);
      }

      // Construct using protobufUtils.ProtobufUtils.PGRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRankInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        requestType_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        requestCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        username_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        score_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        picture_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        picList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        if (rankInfoBuilder_ == null) {
          rankInfo_ = protobufUtils.ProtobufUtils.PGRequest.RankInfo.getDefaultInstance();
        } else {
          rankInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobufUtils.ProtobufUtils.internal_static_protobufUtils_PGRequest_descriptor;
      }

      public protobufUtils.ProtobufUtils.PGRequest getDefaultInstanceForType() {
        return protobufUtils.ProtobufUtils.PGRequest.getDefaultInstance();
      }

      public protobufUtils.ProtobufUtils.PGRequest build() {
        protobufUtils.ProtobufUtils.PGRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobufUtils.ProtobufUtils.PGRequest buildPartial() {
        protobufUtils.ProtobufUtils.PGRequest result = new protobufUtils.ProtobufUtils.PGRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.requestType_ = requestType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.requestCode_ = requestCode_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.username_ = username_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.password_ = password_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.score_ = score_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.picture_ = picture_;
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          picList_ = picList_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.picList_ = picList_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000040;
        }
        if (rankInfoBuilder_ == null) {
          result.rankInfo_ = rankInfo_;
        } else {
          result.rankInfo_ = rankInfoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobufUtils.ProtobufUtils.PGRequest) {
          return mergeFrom((protobufUtils.ProtobufUtils.PGRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobufUtils.ProtobufUtils.PGRequest other) {
        if (other == protobufUtils.ProtobufUtils.PGRequest.getDefaultInstance()) return this;
        if (other.hasRequestType()) {
          bitField0_ |= 0x00000001;
          requestType_ = other.requestType_;
          onChanged();
        }
        if (other.hasRequestCode()) {
          bitField0_ |= 0x00000002;
          requestCode_ = other.requestCode_;
          onChanged();
        }
        if (other.hasUsername()) {
          bitField0_ |= 0x00000004;
          username_ = other.username_;
          onChanged();
        }
        if (other.hasPassword()) {
          bitField0_ |= 0x00000008;
          password_ = other.password_;
          onChanged();
        }
        if (other.hasScore()) {
          bitField0_ |= 0x00000010;
          score_ = other.score_;
          onChanged();
        }
        if (other.hasPicture()) {
          bitField0_ |= 0x00000020;
          picture_ = other.picture_;
          onChanged();
        }
        if (!other.picList_.isEmpty()) {
          if (picList_.isEmpty()) {
            picList_ = other.picList_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensurePicListIsMutable();
            picList_.addAll(other.picList_);
          }
          onChanged();
        }
        if (other.hasRankInfo()) {
          mergeRankInfo(other.getRankInfo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRequestType()) {
          
          return false;
        }
        if (!hasRequestCode()) {
          
          return false;
        }
        if (hasRankInfo()) {
          if (!getRankInfo().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobufUtils.ProtobufUtils.PGRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobufUtils.ProtobufUtils.PGRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object requestType_ = "";
      /**
       * <code>required string requestType = 1;</code>
       *
       * <pre>
       * with values "post" and "get"
       * </pre>
       */
      public boolean hasRequestType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string requestType = 1;</code>
       *
       * <pre>
       * with values "post" and "get"
       * </pre>
       */
      public java.lang.String getRequestType() {
        java.lang.Object ref = requestType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            requestType_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string requestType = 1;</code>
       *
       * <pre>
       * with values "post" and "get"
       * </pre>
       */
      public com.google.protobuf.ByteString
          getRequestTypeBytes() {
        java.lang.Object ref = requestType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string requestType = 1;</code>
       *
       * <pre>
       * with values "post" and "get"
       * </pre>
       */
      public Builder setRequestType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        requestType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string requestType = 1;</code>
       *
       * <pre>
       * with values "post" and "get"
       * </pre>
       */
      public Builder clearRequestType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        requestType_ = getDefaultInstance().getRequestType();
        onChanged();
        return this;
      }
      /**
       * <code>required string requestType = 1;</code>
       *
       * <pre>
       * with values "post" and "get"
       * </pre>
       */
      public Builder setRequestTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        requestType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object requestCode_ = "";
      /**
       * <code>required string requestCode = 2;</code>
       *
       * <pre>
       * for different kind of infomation
       * </pre>
       */
      public boolean hasRequestCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string requestCode = 2;</code>
       *
       * <pre>
       * for different kind of infomation
       * </pre>
       */
      public java.lang.String getRequestCode() {
        java.lang.Object ref = requestCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            requestCode_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string requestCode = 2;</code>
       *
       * <pre>
       * for different kind of infomation
       * </pre>
       */
      public com.google.protobuf.ByteString
          getRequestCodeBytes() {
        java.lang.Object ref = requestCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string requestCode = 2;</code>
       *
       * <pre>
       * for different kind of infomation
       * </pre>
       */
      public Builder setRequestCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        requestCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string requestCode = 2;</code>
       *
       * <pre>
       * for different kind of infomation
       * </pre>
       */
      public Builder clearRequestCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        requestCode_ = getDefaultInstance().getRequestCode();
        onChanged();
        return this;
      }
      /**
       * <code>required string requestCode = 2;</code>
       *
       * <pre>
       * for different kind of infomation
       * </pre>
       */
      public Builder setRequestCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        requestCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object username_ = "";
      /**
       * <code>optional string username = 3;</code>
       *
       * <pre>
       * field for type "post"
       * </pre>
       */
      public boolean hasUsername() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string username = 3;</code>
       *
       * <pre>
       * field for type "post"
       * </pre>
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            username_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string username = 3;</code>
       *
       * <pre>
       * field for type "post"
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string username = 3;</code>
       *
       * <pre>
       * field for type "post"
       * </pre>
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        username_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string username = 3;</code>
       *
       * <pre>
       * field for type "post"
       * </pre>
       */
      public Builder clearUsername() {
        bitField0_ = (bitField0_ & ~0x00000004);
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      /**
       * <code>optional string username = 3;</code>
       *
       * <pre>
       * field for type "post"
       * </pre>
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        username_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>optional string password = 4;</code>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string password = 4;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            password_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string password = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string password = 4;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 4;</code>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000008);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 4;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        password_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object score_ = "";
      /**
       * <code>optional string score = 5;</code>
       */
      public boolean hasScore() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string score = 5;</code>
       */
      public java.lang.String getScore() {
        java.lang.Object ref = score_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            score_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string score = 5;</code>
       */
      public com.google.protobuf.ByteString
          getScoreBytes() {
        java.lang.Object ref = score_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          score_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string score = 5;</code>
       */
      public Builder setScore(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        score_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string score = 5;</code>
       */
      public Builder clearScore() {
        bitField0_ = (bitField0_ & ~0x00000010);
        score_ = getDefaultInstance().getScore();
        onChanged();
        return this;
      }
      /**
       * <code>optional string score = 5;</code>
       */
      public Builder setScoreBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        score_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object picture_ = "";
      /**
       * <code>optional string picture = 6;</code>
       */
      public boolean hasPicture() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string picture = 6;</code>
       */
      public java.lang.String getPicture() {
        java.lang.Object ref = picture_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            picture_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string picture = 6;</code>
       */
      public com.google.protobuf.ByteString
          getPictureBytes() {
        java.lang.Object ref = picture_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          picture_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string picture = 6;</code>
       */
      public Builder setPicture(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        picture_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string picture = 6;</code>
       */
      public Builder clearPicture() {
        bitField0_ = (bitField0_ & ~0x00000020);
        picture_ = getDefaultInstance().getPicture();
        onChanged();
        return this;
      }
      /**
       * <code>optional string picture = 6;</code>
       */
      public Builder setPictureBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        picture_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList picList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePicListIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          picList_ = new com.google.protobuf.LazyStringArrayList(picList_);
          bitField0_ |= 0x00000040;
         }
      }
      /**
       * <code>repeated string picList = 7;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getPicListList() {
        return picList_.getUnmodifiableView();
      }
      /**
       * <code>repeated string picList = 7;</code>
       */
      public int getPicListCount() {
        return picList_.size();
      }
      /**
       * <code>repeated string picList = 7;</code>
       */
      public java.lang.String getPicList(int index) {
        return picList_.get(index);
      }
      /**
       * <code>repeated string picList = 7;</code>
       */
      public com.google.protobuf.ByteString
          getPicListBytes(int index) {
        return picList_.getByteString(index);
      }
      /**
       * <code>repeated string picList = 7;</code>
       */
      public Builder setPicList(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePicListIsMutable();
        picList_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string picList = 7;</code>
       */
      public Builder addPicList(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePicListIsMutable();
        picList_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string picList = 7;</code>
       */
      public Builder addAllPicList(
          java.lang.Iterable<java.lang.String> values) {
        ensurePicListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, picList_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string picList = 7;</code>
       */
      public Builder clearPicList() {
        picList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string picList = 7;</code>
       */
      public Builder addPicListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePicListIsMutable();
        picList_.add(value);
        onChanged();
        return this;
      }

      private protobufUtils.ProtobufUtils.PGRequest.RankInfo rankInfo_ = protobufUtils.ProtobufUtils.PGRequest.RankInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          protobufUtils.ProtobufUtils.PGRequest.RankInfo, protobufUtils.ProtobufUtils.PGRequest.RankInfo.Builder, protobufUtils.ProtobufUtils.PGRequest.RankInfoOrBuilder> rankInfoBuilder_;
      /**
       * <code>optional .protobufUtils.PGRequest.RankInfo rankInfo = 8;</code>
       */
      public boolean hasRankInfo() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional .protobufUtils.PGRequest.RankInfo rankInfo = 8;</code>
       */
      public protobufUtils.ProtobufUtils.PGRequest.RankInfo getRankInfo() {
        if (rankInfoBuilder_ == null) {
          return rankInfo_;
        } else {
          return rankInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .protobufUtils.PGRequest.RankInfo rankInfo = 8;</code>
       */
      public Builder setRankInfo(protobufUtils.ProtobufUtils.PGRequest.RankInfo value) {
        if (rankInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          rankInfo_ = value;
          onChanged();
        } else {
          rankInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .protobufUtils.PGRequest.RankInfo rankInfo = 8;</code>
       */
      public Builder setRankInfo(
          protobufUtils.ProtobufUtils.PGRequest.RankInfo.Builder builderForValue) {
        if (rankInfoBuilder_ == null) {
          rankInfo_ = builderForValue.build();
          onChanged();
        } else {
          rankInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .protobufUtils.PGRequest.RankInfo rankInfo = 8;</code>
       */
      public Builder mergeRankInfo(protobufUtils.ProtobufUtils.PGRequest.RankInfo value) {
        if (rankInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000080) == 0x00000080) &&
              rankInfo_ != protobufUtils.ProtobufUtils.PGRequest.RankInfo.getDefaultInstance()) {
            rankInfo_ =
              protobufUtils.ProtobufUtils.PGRequest.RankInfo.newBuilder(rankInfo_).mergeFrom(value).buildPartial();
          } else {
            rankInfo_ = value;
          }
          onChanged();
        } else {
          rankInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .protobufUtils.PGRequest.RankInfo rankInfo = 8;</code>
       */
      public Builder clearRankInfo() {
        if (rankInfoBuilder_ == null) {
          rankInfo_ = protobufUtils.ProtobufUtils.PGRequest.RankInfo.getDefaultInstance();
          onChanged();
        } else {
          rankInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      /**
       * <code>optional .protobufUtils.PGRequest.RankInfo rankInfo = 8;</code>
       */
      public protobufUtils.ProtobufUtils.PGRequest.RankInfo.Builder getRankInfoBuilder() {
        bitField0_ |= 0x00000080;
        onChanged();
        return getRankInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .protobufUtils.PGRequest.RankInfo rankInfo = 8;</code>
       */
      public protobufUtils.ProtobufUtils.PGRequest.RankInfoOrBuilder getRankInfoOrBuilder() {
        if (rankInfoBuilder_ != null) {
          return rankInfoBuilder_.getMessageOrBuilder();
        } else {
          return rankInfo_;
        }
      }
      /**
       * <code>optional .protobufUtils.PGRequest.RankInfo rankInfo = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          protobufUtils.ProtobufUtils.PGRequest.RankInfo, protobufUtils.ProtobufUtils.PGRequest.RankInfo.Builder, protobufUtils.ProtobufUtils.PGRequest.RankInfoOrBuilder> 
          getRankInfoFieldBuilder() {
        if (rankInfoBuilder_ == null) {
          rankInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              protobufUtils.ProtobufUtils.PGRequest.RankInfo, protobufUtils.ProtobufUtils.PGRequest.RankInfo.Builder, protobufUtils.ProtobufUtils.PGRequest.RankInfoOrBuilder>(
                  getRankInfo(),
                  getParentForChildren(),
                  isClean());
          rankInfo_ = null;
        }
        return rankInfoBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protobufUtils.PGRequest)
    }

    static {
      defaultInstance = new PGRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobufUtils.PGRequest)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobufUtils_PGRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobufUtils_PGRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobufUtils_PGRequest_RankInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobufUtils_PGRequest_RankInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023protobufUtils.proto\022\rprotobufUtils\"\355\001\n" +
      "\tPGRequest\022\023\n\013requestType\030\001 \002(\t\022\023\n\013reque" +
      "stCode\030\002 \002(\t\022\020\n\010username\030\003 \001(\t\022\020\n\010passwo" +
      "rd\030\004 \001(\t\022\r\n\005score\030\005 \001(\t\022\017\n\007picture\030\006 \001(\t" +
      "\022\017\n\007picList\030\007 \003(\t\0223\n\010rankInfo\030\010 \001(\0132!.pr" +
      "otobufUtils.PGRequest.RankInfo\032,\n\010RankIn" +
      "fo\022\016\n\006myRank\030\001 \002(\t\022\020\n\010username\030\002 \003(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobufUtils_PGRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobufUtils_PGRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobufUtils_PGRequest_descriptor,
        new java.lang.String[] { "RequestType", "RequestCode", "Username", "Password", "Score", "Picture", "PicList", "RankInfo", });
    internal_static_protobufUtils_PGRequest_RankInfo_descriptor =
      internal_static_protobufUtils_PGRequest_descriptor.getNestedTypes().get(0);
    internal_static_protobufUtils_PGRequest_RankInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobufUtils_PGRequest_RankInfo_descriptor,
        new java.lang.String[] { "MyRank", "Username", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
